/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#3a494b',
        'error': '#ffb4ab',
        'secondary-fixed': '#efdbff',
        'on-tertiary-fixed-variant': '#464747',
        'primary-container': '#00f2ff',
        'electric-cyan-glow': 'rgba(0, 242, 255, 0.15)',
        'surface-tint': '#00dbe7',
        'on-secondary': '#480081',
        'inverse-surface': '#e5e2e1',
        'outline': '#849495',
        'on-primary': '#00363a',
        'surface-bright': '#3a3939',
        'on-primary-fixed-variant': '#004f54',
        'on-error': '#690005',
        'secondary-container': '#7701d0',
        'secondary': '#dcb8ff',
        'surface-container-highest': '#353534',
        'inverse-primary': '#00696f',
        'tertiary-fixed': '#e3e2e2',
        'surface-dim': '#131313',
        'on-primary-fixed': '#002022',
        'on-secondary-fixed-variant': '#6700b5',
        'surface-container': '#201f1f',
        'background': '#131313',
        'charcoal-surface': '#121212',
        'proton-purple-glow': 'rgba(138, 43, 226, 0.2)',
        'on-error-container': '#ffdad6',
        'surface-container-lowest': '#0e0e0e',
        'on-surface-variant': '#b9cacb',
        'error-container': '#93000a',
        'on-primary-container': '#006a71',
        'on-background': '#e5e2e1',
        'on-tertiary': '#2f3131',
        'on-secondary-container': '#dcb7ff',
        'on-surface': '#e5e2e1',
        'tertiary': '#f8f7f7',
        'surface-container-high': '#2a2a2a',
        'terminal-gray': '#2a2a2a',
        'secondary-fixed-dim': '#dcb8ff',
        'primary': '#e1fdff',
        'tertiary-fixed-dim': '#c6c6c6',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-container': '#5f6060',
        'tertiary-container': '#dbdbdb',
        'primary-fixed': '#74f5ff',
        'on-secondary-fixed': '#2c0051',
        'primary-fixed-dim': '#00dbe7',
        'surface-container-low': '#1c1b1b',
        'surface': '#131313',
        'inverse-on-surface': '#313030',
        'surface-variant': '#353534',
        'tronix-dark': '#050505',
        'tronix-primary': '#00f2ff',
        'tronix-secondary': '#7701d0',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem'
      },
      spacing: {
        'margin-mobile': '16px',
        'base': '8px',
        'section-gap': '120px',
        'margin-desktop': '64px',
        'gutter': '24px'
      },
      fontFamily: {
        sora: ['Sora', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
        'headline-xl': ['Sora', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'code-snippet': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Sora', 'sans-serif'],
        'headline-lg-mobile': ['Sora', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'body-md': ['Inter', 'sans-serif']
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'code-snippet': ['14px', { lineHeight: '1.4', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }]
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'pulse-glow': 'pulse-glow 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'trace': 'trace 3s linear infinite',
        glow: 'glow 2s ease-in-out infinite',
        pulseFade: 'pulseFade 3s ease-in-out infinite',
        'fade-in-up': 'fadeInUp 0.8s ease-out forwards',
        blob: 'blob 7s infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        },
        'pulse-glow': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '.5' },
        },
        trace: {
          '0%': { strokeDashoffset: '1000' },
          '100%': { strokeDashoffset: '0' },
        },
        glow: {
          '0%, 100%': { 'text-shadow': '0 0 5px #00f7ff, 0 0 10px #00f7ff, 0 0 20px #00f7ff' },
          '50%': { 'text-shadow': '0 0 10px #00f7ff, 0 0 25px #00f7ff, 0 0 40px #00f7ff' },
        },
        pulseFade: {
          '0%, 100%': { opacity: '0.8', transform: 'scale(1)' },
          '50%': { opacity: '1', transform: 'scale(1.03)' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        blob: {
          '0%': { transform: 'translate(0px, 0px) scale(1)' },
          '33%': { transform: 'translate(30px, -50px) scale(1.1)' },
          '66%': { transform: 'translate(-20px, 20px) scale(0.9)' },
          '100%': { transform: 'translate(0px, 0px) scale(1)' },
        },
      }
    },
  },
  plugins: [],
}
